DXDIR := /home/shyuan/.opam/4.11.1/lib/dx
COMPCERTDIR := /home/shyuan/GitLab/CompCertBin/compcert
CLIGHTGEN32DIR := /home/shyuan/GitLab/CompCertBin/compcert
COMPCERTSRCDIR := /home/shyuan/GitLab/CompCertBin/compcert
